title: "Моето CV"
description: "Персонално CV на Кристиана Костова"
theme: jekyll-theme-hacker
markdown: kramdown
url: "https://kristianakostova015.github.io"
repository: "https://github.com/KristianaKostova015/kristianakostova.github.io"
